version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing Yarn...
      - npm install -g yarn
    pre_build:
      commands:
        - echo Installing dependencies...
        - yarn install
    build:
      commands:
        - echo Building...
        - yarn build
cache:
  paths:
    - './node_modules/**/*'

